### ISSUE TITLE
Error - Call to a member function set() on a non-object 

### ISSUE THREAD

**Issue by zballos** [bravo-kernel/application-examples#3]
Hi. 

I followed all the steps of the tutorial, but when I test /register data is registered but appears this error and does not return the token.
I have not figured out the cause of the error.

> Error: Call to a member function set() on a non-object 
> File /var/www/html/project/vendor/friendsofcake/crud/src/Action/BaseAction.php 
> Line: 193

**Comment by bravo-kernel** [comment]
@zballos it seems I missed some things while updating the application sources. I have just corrected and tested each application. All bugs have been resolved. Also... you will now find a Postman collection you can use, it contains all the API calls used in the tutorials.

**Comment by srinivasaltair** [comment]
Hi @bravo-kernel please let me know what changes that we are suppose to make the error fix. I followed all the method in your application. But this error I am not able to fix.

> Error: Call to a member function set() on a non-object 
> File /var/www/html/project/vendor/friendsofcake/crud/src/Action/BaseAction.php 
> Line: 193

**Comment by rohitmbnitk** [comment]
@bravo-kernel @srinivasaltair please let me the steps to fix this.
