### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by Drakota** [bravo-kernel/application-examples#6]
Hi, I was following your tutorial and everything went fine until step 9. I couldn't log in with good credentials. In my database, I do not have a username, but an email. (Step 7 works, it generates a token)
```
$this->loadComponent('Auth', [
      'storage' => 'Memory',
            'authenticate' => [
                'ADmad/JwtAuth.Jwt' => [
                    'parameter' => 'token',
                    'userModel' => 'Users',
                    'fields' => [
                        'username' => 'email',
		        'password' => 'password'
                    ],
                    'queryDatasource' => true
                ]
            ],
            'unauthorizedRedirect' => false,
            'checkAuthIn' => 'Controller.initialize',
        ]);

```
In your tutorial 'fields' has 'username' => 'id', I tried changing it to 'email', but doesn't work.
How can I fix this problem?

**Comment by Drakota** [comment]
I tried resolving the problem and I cannot find where is the problem, It just won't work with an email. Even though I followed the tutorial with the only exception that I don't use an username. @bravo-kernel

**Comment by bravo-kernel** [comment]
You are probably defining `email` in the wrong place.

Here's a working example taken from one of my apps, maybe it helps.

```php
            'authenticate' => [
                'Form' => [
                    'fields' => ['username' => 'email', 'password' => 'password']
                ],
                'ADmad/JwtAuth.Jwt' => [
                    'finder' => 'obfuscated',
                    'userModel' => 'Users',
                    'fields' => [
                        'username' => 'id'
                    ],
                    'parameter' => 'token',
                    'queryDatasource' => true // must be true, see docblock
                ]
            ],
```

**Comment by Drakota** [comment]
Hey again ! It worked, but I had  to change 
```
'token' => JWT::encode([
      'sub' => $user['email'],
      'exp' =>  time() + 604800
],
```
`$user['id'] to ['email']`

Thanks 👍 

EDIT: 

Had to change username back to email, because the token contains the email not the id when using jwt.io to test the tokens.
```
'ADmad/JwtAuth.Jwt' => [
        'userModel' => 'Users',
        'fields' => [
        'username' => 'email'
        ],

        'parameter' => 'token',
        'queryDatasource' => true,
]
```

**Comment by bravo-kernel** [comment]
Good to hear and thank you for adding the solution mr. @Drakota
